version: "3.3"

networks:
  net:
    driver: bridge

services:
  postgres:
    image: postgres:15.1
    env_file: .env
    container_name: 'postgres-container'
    ports:
      - 5432:5432
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - net

  backend:
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: 'backend-container'
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: ./app
    depends_on:
      - postgres
    networks:
      - net
